"""AI-powered brain area segmentation.

Provides prediction functions using trained deep learning models
with automatic fallback to Otsu thresholding when no model
checkpoint is available.
"""

import os
from typing import Optional

import nibabel as nib
import numpy as np


def predict_segmentation(
    image: np.ndarray,
    model_path: Optional[str] = None,
) -> np.ndarray:
    """Predict a binary brain segmentation mask from a 3D volume.

    When *model_path* is provided the function attempts to load a
    pre-trained model for inference.  If no model is available (or
    loading fails) it falls back to Otsu thresholding, which
    separates foreground (brain tissue) from background.

    Args:
        image: 3D numpy array.
        model_path: Optional path to a saved model checkpoint.
            If ``None``, Otsu thresholding is used automatically.

    Returns:
        Binary mask array with the same shape as *image*.

    Raises:
        FileNotFoundError: If *model_path* is set but does not exist.
    """
    if model_path is not None:
        return _predict_with_model(image, model_path)
    return _predict_fallback(image)


def segment_brain(
    file_path: str,
    output_path: Optional[str] = None,
) -> str:
    """Segment a NIfTI brain volume and save the result.

    Reads the NIfTI file at *file_path*, runs brain segmentation
    (via trained model or Otsu fallback), and writes the binary
    mask to *output_path*.  If *output_path* is ``None`` a default
    path is generated by appending ``_seg`` to the stem.

    Args:
        file_path: Path to the input NIfTI file (``.nii`` or
            ``.nii.gz``).
        output_path: Path for the output segmentation.  Defaults to
            ``<stem>_seg.nii.gz``.

    Returns:
        The absolute path where the segmentation was saved.
    """
    if not os.path.isfile(file_path):
        raise FileNotFoundError(f"Input file not found: {file_path}")

    img = nib.load(file_path)
    data = img.get_fdata()

    mask = predict_segmentation(np.asarray(data, dtype=np.float32))

    if output_path is None:
        base, _ = os.path.splitext(file_path)
        if base.endswith(".nii"):
            base = base[:-4]
        output_path = base + "_seg.nii.gz"

    seg_img = nib.Nifti1Image(mask.astype(np.float32), img.affine)
    nib.save(seg_img, output_path)
    return os.path.abspath(output_path)


def _predict_with_model(
    image: np.ndarray,
    model_path: str,
) -> np.ndarray:
    """Run inference with a trained PyTorch model checkpoint.

    Attempts to load and apply a saved model.  If the architecture
    cannot be determined a ``NotImplementedError`` is raised with
    guidance to use the Otsu fallback instead.
    """
    if not os.path.isfile(model_path):
        raise FileNotFoundError(f"Model file not found: {model_path}")

    try:
        import torch
    except ImportError:
        raise ImportError(
            "PyTorch is required to load a trained model. "
            "Install it with `pip install torch` or omit "
            "*model_path* to use Otsu thresholding."
        )

    checkpoint = torch.load(
        model_path, map_location="cpu", weights_only=False
    )

    if hasattr(checkpoint, "eval") and callable(getattr(checkpoint, "eval", None)):
        model = checkpoint
    elif isinstance(checkpoint, dict) and "state_dict" in checkpoint:
        raise NotImplementedError(
            "Cannot load model from state_dict checkpoint — "
            "no model architecture is defined in AI_area_split. "
            "Use *model_path=None* for Otsu thresholding instead."
        )
    elif isinstance(checkpoint, dict):
        raise NotImplementedError(
            "Unrecognised dictionary checkpoint. "
            "Use *model_path=None* for Otsu thresholding instead."
        )
    else:
        raise NotImplementedError(
            "Unknown checkpoint format. "
            "Use *model_path=None* for Otsu thresholding instead."
        )

    model.eval()
    tensor = torch.from_numpy(np.asarray(image, dtype=np.float32))
    if tensor.ndim == 3:
        tensor = tensor.unsqueeze(0).unsqueeze(0)
    elif tensor.ndim == 4:
        tensor = tensor.unsqueeze(0)

    with torch.no_grad():
        output = model(tensor)
        mask = (output.squeeze().cpu().numpy() > 0.5).astype(image.dtype)

    return mask


def _predict_fallback(image: np.ndarray) -> np.ndarray:
    """Segment brain tissue using Otsu thresholding.

    Tries SimpleITK first, then falls back to scikit-image.
    """
    try:
        import SimpleITK as sitk
        sitk_image = sitk.GetImageFromArray(
            np.asarray(image, dtype=np.float32)
        )
        mask_image = sitk.OtsuThreshold(sitk_image, 0, 1)
        return sitk.GetArrayFromImage(mask_image).astype(image.dtype)
    except ImportError:
        pass

    import skimage as ski
    data = np.asarray(image, dtype=np.float32)
    thresh = ski.filters.threshold_otsu(data)
    return (data > thresh).astype(image.dtype)
