# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os.path
import sys
import platform
import numpy as np
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QProcess
from PyQt6.QtWidgets import QMessageBox,QInputDialog
import pyvista;
#GUI part still under construction
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(615, 569)
        Dialog.setAutoFillBackground(True)
        Dialog.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(170, 480, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.toolButton = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton.setGeometry(QtCore.QRect(70, 0, 41, 31))
        self.toolButton.setObjectName("toolButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(parent=Dialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(290, 30, 172, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.toolButton_2 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_2.setGeometry(QtCore.QRect(10, 0, 51, 31))
        self.toolButton_2.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_3.setGeometry(QtCore.QRect(310, 0, 31, 31))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_4.setGeometry(QtCore.QRect(120, 0, 61, 31))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_5.setGeometry(QtCore.QRect(190, 0, 31, 31))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_6.setGeometry(QtCore.QRect(230, 0, 31, 31))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_7 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_7.setGeometry(QtCore.QRect(270, 0, 31, 31))
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_8.setGeometry(QtCore.QRect(120, 40, 41, 31))
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_9 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_9.setGeometry(QtCore.QRect(170, 40, 31, 31))
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_10 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_10.setGeometry(QtCore.QRect(20, 40, 41, 31))
        self.toolButton_10.setObjectName("toolButton_10")
        self.toolButton_11 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_11.setGeometry(QtCore.QRect(70, 40, 41, 31))
        self.toolButton_11.setObjectName("toolButton_11")
        self.toolButton_12 = QtWidgets.QToolButton(parent=Dialog)
        self.toolButton_12.setGeometry(QtCore.QRect(210, 40, 71, 31))
        self.toolButton_12.setObjectName("toolButton_12")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(200, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(50, 90, 131, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(200, 130, 104, 21))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(200, 160, 104, 21))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(200, 190, 104, 21))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 230, 271, 241))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.checkBox = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox.setGeometry(QtCore.QRect(320, 240, 85, 20))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(320, 280, 85, 20))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(320, 320, 85, 20))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(320, 360, 85, 20))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(320, 400, 85, 20))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(320, 440, 85, 20))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(340, 280, 91, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(450, 280, 81, 31))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(460, 320, 81, 31))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(340, 320, 111, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.save_path=None;
        self.i=0;
        self.color=None;
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.toolButton.setText(_translate("Dialog", "设置"))
        self.commandLinkButton.setText(_translate("Dialog", "命令行模式"))
        self.toolButton_2.setText(_translate("Dialog", "文件"))
        self.toolButton_3.setText(_translate("Dialog", "关于"))
        self.toolButton_4.setText(_translate("Dialog", "可视化"))
        self.toolButton_5.setText(_translate("Dialog", "工具"))
        self.toolButton_6.setText(_translate("Dialog", "AI助手"))
        self.toolButton_7.setText(_translate("Dialog", "帮助"))
        self.toolButton_8.setText(_translate("Dialog", "3D"))
        self.toolButton_9.setText(_translate("Dialog", "2D"))
        self.toolButton_10.setText(_translate("Dialog", "打开"))
        self.toolButton_11.setText(_translate("Dialog", "保存"))
        self.toolButton_12.setText(_translate("Dialog", "显示详细信息"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">脑表面文件路径</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Node文件路径</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Edge 文件路径</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">图像文件路径</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">是否通过图像生成脑表面与脑区（耗时预计数小时）</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">是否通过图像序列生成连接矩阵（耗时数分钟到半小时）</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">是否进行配准（耗时1分钟至数分钟）                    </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">是否使用AI超分辨率算法进行图像处理</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">是否使用实验性AI脑区分割</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">是否使用实验性AI配准算法</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">图像序列路径</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">配准参考文件路径</p></body></html>"))


    def open_terminal(self):
        """根据操作系统启动终端"""
        system = platform.system()

        if system == "Windows":
            # Windows 启动 cmd
            QProcess.startDetached("cmd.exe")
        elif system == "Linux":
            # Linux 启动 gnome-terminal（需确保已安装）
            QProcess.startDetached("gnome-terminal")
        elif system == "Darwin":
            # macOS 启动 Terminal.app
            QProcess.startDetached("open", ["-a", "Terminal"])
        else:
            print("不支持的操作系统")
    def getargs(self):
        surfacep=self.plainTextEdit.toPlainText()
        nodep=self.plainTextEdit_2.toPlainText()
        edgep=self.plainTextEdit_3.toPlainText()
        imagep=self.plainTextEdit_4.toPlainText();
        imageseqp=self.plainTextEdit_5.toPlainText();
        correfp=self.plainTextEdit_6.toPlainText()
        freesurfer=self.checkBox.isChecked();
        connectmatix=self.checkBox_2.isChecked();
        cor=self.checkBox_3.isChecked();
        superres=self.checkBox_4.isChecked();
        aisplit=self.checkBox_5.isChecked();
        aicorrect=self.checkBox_6.isChecked();
        return {"surfacep":surfacep,"nodep":nodep,"edgep":edgep,"imagep":imagep,"imageseqp":imageseqp,"correfp":correfp,"freesurfer":freesurfer,"connectmatix":connectmatix,"cor":cor,"superres":superres,"aisplit":aisplit,"aicorrect":aicorrect};

    def argrun(self):
        args=self.getargs();
        if(args["aisplit"] or args["aicorrect"]):
            QMessageBox.information(text="Still not supported!");
        if(args["freesurfer"]):
            import free_surfer.api;
            allpath=args['imagep'];
            if(allpath is None or allpath==""):
                QMessageBox.information(text="Path Error!")
            else:
                splitindex=allpath.rfind("/");
                if(splitindex=="-1"):
                    QMessageBox.information(text="path index error!");
                else:
                    path=allpath[:splitindex];
                    name=allpath[splitindex+1:];
                    free_surfer.api.split(path,name,os.path.join(path,"split"));
        if(args["connectmatrix"]):
            import con_mat_cal_nilearn;
            matrix=con_mat_cal_nilearn.getcor_matrix(args["imageseqp"]);
            np.save(args["edgep"],matrix);
        if(args["cor"]):
            import correct_elastix.api;
            correct_elastix.api.correct_from_path(args["imagep"],args["correfp"],args["imagep"]);
        if(args["superres"]):
            import super_res.api;
            super_res.api.run_inference(args["imagep"],savepath=args["imagep"]);
        if(args["nodep"] is None or args["nodep"]==""):
            if(args["surfacep"] is None or args["surfacep"]==""):
                QMessageBox.information(text="Error! No node and surface file path!");
                QMessageBox.information(text="We will not plot anything!")
            else:
                import Draw;
                mesh=Draw.drawsurface(args["surfacep"],args["imagep"]);
                if(self.save_path is not None):
                    mesh.save_graphic(self.save_path);

        else:
            import Draw;
            if(self.color==None):
                colortype=("red","blue","green");
            else:
                colortype=self.color;
            mesh=Draw.drawnode(args["nodep"],args["edgep"],args["surfacep"],args["imagep"],colortype=colortype);
            if(self.save_path is not None):
                mesh.save_graphic(self.save_path);
    def ai_assisetent(self):
        #still under construction, this is a demo
        import AI_LLM_ASK;
        QMessageBox.information(text="Welcome to AI Assisetent, Please input API key");
        api,ok=QInputDialog.getText(title="apikey",content="Please input apikey");
        if(ok):
            content,ok2=QInputDialog.getText(title="content",content="Please input your content");
            if(ok2):
                message=[{"role": "user", "content": content}];
                QMessageBox.information(text=AI_LLM_ASK.call(message=message,apikey=api));
    def save(self):
        self.save_path=os.curdir+f"/mesh{self.i}";
        self.i+=1;
    def help(self):
        QMessageBox.information(text="You can choose several path input, the software will generate others if you choose the processing tools");
    def about(self):
        QMessageBox.information(text="PyBrainImageTools Version 0.0.1 beta");
        QMessageBox.information(text="By Azuma from ShanghaiTech University");
    def setcolor(self):
        QMessageBox.information(text="input your color for nodes,edges and surface");
        color,ok=QInputDialog.getText(title="color",content="Please input your color");
        if(ok):
            self.color=tuple(color.split(","));
    def run(self):
        self.commandLinkButton.clicked.connect(self.open_terminal)
        self.buttonBox.accepted.connect(self.argrun);
        self.buttonBox.rejected.connect(sys.exit);
        self.toolButton_11.clicked.connect(self.save);
        self.toolButton_7.clicked.connect(self.help);
        self.toolButton_3.clicked.connect(self.about);
        self.toolButton_6.clicked.connect(self.ai_assisetent);
        self.toolButton_4.clicked.connect(self.setcolor)
        #others still under construction


